import type { PickierOptions } from 'pickier'

const config: PickierOptions = {
  // pickier merges `ignores` with a "replace" strategy, so the defaults must be
  // restated here alongside our additions.
  ignores: [
    '**/node_modules/**',
    '**/.pnpm/**',
    '**/.yarn/**',
    '**/dist/**',
    '**/build/**',
    '**/out/**',
    '**/.output/**',
    '**/.next/**',
    '**/.nuxt/**',
    '**/.vite/**',
    '**/.turbo/**',
    '**/.cache/**',
    '**/coverage/**',
    '**/vendor/**',
    '**/pantry/**',
    '**/tmp/**',
    '**/.git/**',
    '**/.idea/**',
    '**/.vscode/**',
    '**/.zed/**',
    '**/.cursor/**',
    '**/.claude/**',
    '**/.github/**',
    '**/*.test.ts',
    '**/*.spec.ts',
    '**/.bunpress/**',
    '**/.vitepress/cache/**',
    '**/*.lock',
    '**/package-lock.json',
    '**/pnpm-lock.yaml',

    // Generated by logsmith on release.
    '**/CHANGELOG.md',
    // Generated/fixture output written by the scaffold + loader tests.
    '**/test/outputs/**',
    // HTML attributes are conventionally double-quoted; pickier's `quotes` rule
    // forces single quotes with no per-extension override, so skip HTML files.
    '**/*.html',
  ],
  pluginRules: {
    // `dist` is built at publish time, not before lint, so the bin/types/exports
    // targets legitimately don't exist when linting the source tree.
    'publint/file-does-not-exist': 'off',
    // The README intentionally mixes reference-style badges with inline links.
    'markdown/link-image-style': 'off',
  },
}

export default config
