// Auto-generated by ts-i18n. Do not edit.
import type { DotPaths, ParamsForKey, TranslatorFor } from 'ts-i18n'
import * as Mod from "/Users/chrisbreuer/Code/Libraries/ts-i18n/packages/ts-i18n/test/fixtures/locales/en/index.ts"

type Base = (
  Mod extends { default: infer D } ? D :
  Mod extends { translations: infer T } ? T :
  Mod
) extends infer X ? X : never

export type TranslationKey = DotPaths<Base>
export type ParamsFor<K extends TranslationKey> = ParamsForKey<Base, K>
export type TypedTranslator = TranslatorFor<Base>
